### ISSUE TITLE
Не стоит объявлять функции в рендере

### ISSUE THREAD

**Issue by codyfet** [vladimirzhirov/testapp#10]
https://github.com/vladimirzhirov/testapp/blob/64a2829a02419f95d85f2ff14e5c8b4103e0e7e9/src/components/country-card.js#L14

Рендер вызывается много раз, и каждый раз у тебя будет создаваться новая функция, а значит создаваться  новый объект в памяти. Это нехорошо.
Лучше вынеси эту функцию в метод handleMouseDown и там уже положи код, который тебе нужно.
В рендере просто присвоишь как обычно:
```
onMouseDown={this.handleMouseDown}
```

**Comment by vladimirzhirov** [comment]
исправлено
