### ISSUE TITLE
Лишний конструктор

### ISSUE THREAD

**Issue by codyfet** [vladimirzhirov/testapp#11]
https://github.com/vladimirzhirov/testapp/blob/64a2829a02419f95d85f2ff14e5c8b4103e0e7e9/src/components/country-card.js#L6

Если у тебя нет логику, которую нужно выполнить в конструкторе, то и конструктор писать не нужно (вызовется конструктор по умолчанию). 

Просто лишний код.

И кстати, этот компонент можно было бы реализовать как функциональный.
Нужно стремится делать все компоненты функциональными, которые возможно сделать таковыми (у которы нет стейта и методов жц). Будущее за функциональными компонентами (см. react hooks)

**Comment by JohnFrolov** [comment]
Хуки рулят :)

**Comment by vladimirzhirov** [comment]
Сделать компонент-обертку над SmartSelect куда вынести всю логику по загрузке данных ?

SmartSelect и CountryCard сделать "глупыми" компонентами без своего state ?

**Comment by vladimirzhirov** [comment]
ok
