### ISSUE TITLE
Можно сделать функциональным

### ISSUE THREAD

**Issue by codyfet** [vladimirzhirov/testapp#13]
https://github.com/vladimirzhirov/testapp/blob/64a2829a02419f95d85f2ff14e5c8b4103e0e7e9/src/components/panel.js#L16

```
export const Panel = () => <SmartSelect />;
```

:D вот и весь твой компонент (если нужна обертка то тогда еще оберни в div а лучше в <React.Fragment></React.Fragment>

**Comment by vladimirzhirov** [comment]
ок
