### ISSUE TITLE
Минорная правка. везде стрелочные а тут function:(

### ISSUE THREAD

**Issue by JohnFrolov** [vladimirzhirov/testapp#14]
https://github.com/vladimirzhirov/testapp/blob/64a2829a02419f95d85f2ff14e5c8b4103e0e7e9/src/components/smart-select.js#L89

Для порядка поправить бы.

**Comment by codyfet** [comment]
Да, могут быть неприятности, если в этой функции захочешь this использовать (так как у такой функции свой контекств вызова в отличии от стрелочной,)

**Comment by JohnFrolov** [comment]
А зачем underscore?
Стандартный map тоже прекрастно работает :)
+ map можно this передать 4 парамитром :)

**Comment by vladimirzhirov** [comment]
исправлено

**Comment by codyfet** [comment]
> А зачем underscore?
> Стандартный map тоже прекрастно работает :)
> 
> * map можно this передать 4 парамитром :)

не знал, прикольно если так работает)
