### ISSUE TITLE
Несколько setState подряд. 

### ISSUE THREAD

**Issue by JohnFrolov** [vladimirzhirov/testapp#15]
https://github.com/vladimirzhirov/testapp/blob/64a2829a02419f95d85f2ff14e5c8b4103e0e7e9/src/components/smart-select.js#L40-L44

setState() не всегда сразу обновляет компонент. Обновления могут проходить батчем или одложиться на потом. Поэтому потенциально это фейл.
подробнее [тут](https://reactjs.org/docs/react-component.html#setstate) 
![image](https://user-images.githubusercontent.com/4136877/53761559-e2c51100-3ed6-11e9-965a-cb0d7b8b6f5c.png)

**Comment by vladimirzhirov** [comment]
ок

**Comment by vladimirzhirov** [comment]
еще не делал push в ветку

**Comment by JohnFrolov** [comment]
Практика закрывать issue до пуша не очень хорошая 
Я его переотрывать не буду (твой репо твои правила :) ).
