### ISSUE TITLE
Идея прикольноя. Но немного сложно.

### ISSUE THREAD

**Issue by JohnFrolov** [vladimirzhirov/testapp#21]
https://github.com/vladimirzhirov/testapp/blob/2c723460cf12a7b2e68adb80fb44c93aac9e2e7c/src/components/smartSelect/smartSelect.jsx#L12-L16

По названию не очень понятно что происходит
ну и лучше не сокращать парамитры в этом случае
cond это не самое очевидное имя.

**Comment by vladimirzhirov** [comment]
исправил
