### ISSUE TITLE
Не нужно рендерить компоненты которых нет.

### ISSUE THREAD

**Issue by JohnFrolov** [vladimirzhirov/testapp#22]
https://github.com/vladimirzhirov/testapp/blob/2c723460cf12a7b2e68adb80fb44c93aac9e2e7c/src/components/smartSelect/smartSelect.jsx#L36
![image](https://user-images.githubusercontent.com/4136877/54050790-2aa6a980-41f1-11e9-8ffe-15f5dc24580e.png)

**Comment by vladimirzhirov** [comment]
исправлено

**Comment by JohnFrolov** [comment]
я чет не понял как ты это поправил :(
