### ISSUE TITLE
Неправильная работа с обработчиками и событиями

### ISSUE THREAD

**Issue by codyfet** [vladimirzhirov/testapp#6]
https://github.com/vladimirzhirov/testapp/blob/157937d1927eda481d0fb9f6216f929404de2172/src/components/smart-select.js#L20

Вот это прям совсем совсем не реакт-way. Так делать не стоит

До конца не понял зачем это здесь, но компонеты должны строиться иерархически (один в другом). Если нужно навесить onClick обработчик куда то - просто добавляй пропсу компоненту что то типа:
```
<div onClick={this.handleClick}>
    ....
</div>
```
и никак иначе

**Comment by vladimirzhirov** [comment]
Это нужно для того, чтобы закрывать меню при клике вне области компонента выбора стран

**Comment by vladimirzhirov** [comment]
исправлено
