### ISSUE TITLE
Неправильная работа с dom элементами

### ISSUE THREAD

**Issue by codyfet** [vladimirzhirov/testapp#7]
https://github.com/vladimirzhirov/testapp/blob/157937d1927eda481d0fb9f6216f929404de2172/src/components/smart-select.js#L92

Это тоже совсем не "по реакту".
Вся информация должна храниться в стейте компонент. Например, создай свойство inputValue в стейте, а там где у тебя рисуется сам input - бери оттуда данные:
```
<input 
    value={this.state.inputValue}
    onChange={this.handleInputChange}
/>
```
Соответственно handleInputChange может выглядеть так:
```
handleInputChange = (event) => {
    this.setState({
        inputValue: event.target.value
    });
}
```

**Comment by vladimirzhirov** [comment]
исправлено
