### ISSUE TITLE
Можно не создавать div для обертки

### ISSUE THREAD

**Issue by codyfet** [vladimirzhirov/testapp#8]
https://github.com/vladimirzhirov/testapp/blob/64a2829a02419f95d85f2ff14e5c8b4103e0e7e9/src/components/panel.js#L11

В какой то версии реакта появилась возможность вметос элемента обертки использовать такую запись:

```
<React.Fragment>
    <SmartCard />
</React.Fragment>
```

Этот подход лучше, так как в итоговом html у тебя не будет лишних ненужных элементов.

**Comment by vladimirzhirov** [comment]
исправлено
