### ISSUE TITLE
Ни к чему использовать стрелочные функции всегда для методов

### ISSUE THREAD

**Issue by codyfet** [vladimirzhirov/testapp#9]
https://github.com/vladimirzhirov/testapp/blob/64a2829a02419f95d85f2ff14e5c8b4103e0e7e9/src/components/smart-select.js#L16

Хорошей  практикой считается реализовывать методы класса через стрелочные функции лишь тогда, когда это необходимо (когда мы решаем проблему с контекстом). В данном случае лучше было бы написать:

```
    checkInputValue (value) {
        return value.length > 2;
    };
```

**Comment by codyfet** [comment]
И если все таки через стрелку решил сделать то можно еще проще))

```
checkInputValue = (value) => value.length > 2;
```

**Comment by vladimirzhirov** [comment]
исправлено
